# Generated by Django 4.2.7 on 2026-05-07 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PTP', '0018_expopushtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='expo_push_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
