# Generated by Django 4.2.7 on 2026-05-07 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PTP', '0019_driver_expo_push_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('user_type', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('unread', 'Unread'), ('read', 'Read')], default='unread', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'notification',
            },
        ),
    ]
