# Generated by Django 4.2.7 on 2026-05-07 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PTP', '0020_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expopushtoken',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='expopushtoken',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
