# Generated by Django 4.2.7 on 2026-05-07 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PTP', '0021_remove_expopushtoken_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user_id',
        ),
        migrations.AddField(
            model_name='expopushtoken',
            name='driver',
            field=models.OneToOneField(blank=True, db_column='driver_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expo_push_token_obj', to='PTP.driver'),
        ),
        migrations.AddField(
            model_name='expopushtoken',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='expopushtoken',
            name='user_type',
            field=models.CharField(choices=[('passenger', 'Passenger'), ('driver', 'Driver')], default='passernger', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='driver_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='passenger_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='push_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='push_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='expopushtoken',
            name='token',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='expopushtoken',
            name='user',
            field=models.OneToOneField(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expo_push_token', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('unread', 'Unread'), ('read', 'Read')], db_index=True, default='unread', max_length=10),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user_type',
            field=models.CharField(choices=[('passenger', 'Passenger'), ('driver', 'Driver')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='expopushtoken',
            constraint=models.UniqueConstraint(fields=('token',), name='unique_expo_token'),
        ),
        migrations.AlterModelTable(
            name='expopushtoken',
            table='expo_push_token',
        ),
    ]
