# Generated by Django 4.2.7 on 2026-05-07 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PTP', '0022_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='expo_push_token',
        ),
    ]
