# Generated by Django 4.2.7 on 2026-07-22 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PTP', '0023_remove_driver_expo_push_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='capacity',
            field=models.PositiveIntegerField(default=50, help_text='Maximum number of passengers this vehicle can hold.'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='passenger_count',
            field=models.PositiveIntegerField(default=0, help_text='Current number of passengers on board. Updated by the AI camera service.'),
        ),
    ]
