# Generated by Django 4.2.7 on 2026-07-22 19:48

import PTP.models.scanner_device
import PTP.models.transport_card
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PTP', '0024_vehicle_capacity_vehicle_passenger_count'),
    ]

    operations = [
       
        migrations.CreateModel(
            name='TransportCard',
            fields=[
                ('card_id', models.AutoField(db_column='card_id', primary_key=True, serialize=False)),
                ('card_number', models.CharField(default=PTP.models.transport_card._generate_card_number, help_text='16-digit card number printed on the physical card.', max_length=20, unique=True)),
                ('qr_token', models.CharField(default=PTP.models.transport_card._generate_qr_token, help_text='Opaque token encoded in the QR code. Contains NO user data.', max_length=20, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, help_text='Current prepaid balance in local currency.', max_digits=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('blocked', 'Blocked')], default='inactive', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(help_text='The passenger this card belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='transport_card', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'transport_card',
            },
        ),
        migrations.CreateModel(
            name='TopUpTransaction',
            fields=[
                ('transaction_id', models.AutoField(db_column='transaction_id', primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount added to the card balance.', max_digits=10)),
                ('balance_before', models.DecimalField(decimal_places=2, help_text='Card balance before this top-up.', max_digits=10)),
                ('balance_after', models.DecimalField(decimal_places=2, help_text='Card balance after this top-up.', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_up_transactions', to='PTP.transportcard')),
                ('merchant', models.ForeignKey(help_text='The merchant/kiosk operator who performed the recharge.', on_delete=django.db.models.deletion.CASCADE, related_name='top_up_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'top_up_transaction',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScannerDevice',
            fields=[
                ('device_id', models.AutoField(db_column='device_id', primary_key=True, serialize=False)),
                ('device_code', models.CharField(help_text='Human-readable device identifier. Example: BUS_DEVICE_01', max_length=50, unique=True)),
                ('secret_key', models.CharField(default=PTP.models.scanner_device._generate_secret_key, help_text='Secret key sent in X-Device-Secret header for authentication.', max_length=40, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.OneToOneField(help_text='The bus this payment terminal is installed in.', on_delete=django.db.models.deletion.CASCADE, related_name='scanner_device', to='PTP.vehicle')),
            ],
            options={
                'db_table': 'scanner_device',
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('transaction_id', models.AutoField(db_column='transaction_id', primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Fare amount deducted from the card.', max_digits=10)),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('insufficient_balance', 'Insufficient Balance'), ('card_inactive', 'Card Inactive')], default='success', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='PTP.transportcard')),
                ('device', models.ForeignKey(help_text='The bus payment terminal that scanned the card.', on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='PTP.scannerdevice')),
                ('route', models.ForeignKey(help_text='The route whose price was charged.', on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='PTP.route')),
                ('trip', models.ForeignKey(help_text='The active trip during which the payment occurred.', on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='PTP.drivertrip')),
            ],
            options={
                'db_table': 'payment_transaction',
                'ordering': ['-created_at'],
            },
        ),
    ]
