# Generated by Django 4.2.7 on 2026-07-23 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PTP', '0025_user_role_transportcard_topuptransaction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantProfile',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'address',
                    models.CharField(max_length=255),
                ),
                (
                    'created_at',
                    models.DateTimeField(auto_now_add=True),
                ),
                (
                    'merchant',
                    models.OneToOneField(
                        limit_choices_to={'role': 'merchant'},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='merchant_profile',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'db_table': 'merchant_profile',
            },
        ),
    ]