# Generated by Django 4.2.7 on 2026-07-23 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PTP', '0026_user_role_merchantprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('passenger', 'Passenger'), ('merchant', 'Merchant'), ('admin', 'Admin')], default='passenger', max_length=20),
        ),
    ]
