# Generated by Django 4.2.7 on 2026-07-31 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PTP', '0027_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivertrip',
            name='route_alert_sent',
            field=models.BooleanField(default=False),
        ),
    ]
