# Generated by Django 4.2.7 on 2026-08-04 14:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('PTP', '0028_drivertrip_route_alert_sent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('zone_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('damascus', 'Damascus'), ('suburbs', 'Damascus Suburbs'), ('rural', 'Damascus Rural')], max_length=50, unique=True)),
                ('level', models.PositiveIntegerField(default=1, help_text='Higher level subscription covers lower levels.')),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'zone',
            },
        ),
        migrations.AddField(
            model_name='transportcard',
            name='subscription_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transportcard',
            name='subscription_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Transaction amount. Zero for subscription-based rides.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('insufficient_balance', 'Insufficient Balance'), ('card_inactive', 'Card Inactive'), ('subscription_expired', 'Subscription Expired'), ('zone_not_allowed', 'Zone Not Allowed'), ('no_subscription', 'No Subscription')], default='success', max_length=30),
        ),
        migrations.CreateModel(
            name='ZoneSubscription',
            fields=[
                ('subscription_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_subscriptions', to='PTP.transportcard')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='PTP.zone')),
            ],
            options={
                'db_table': 'zone_subscription',
            },
        ),
        migrations.AddField(
            model_name='route',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='routes', to='PTP.zone'),
        ),
        migrations.AddField(
            model_name='transportcard',
            name='subscription_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cards', to='PTP.zone'),
        ),
    ]
