# Generated by Django 4.2.7 on 2026-08-04 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PTP', '0029_zone_transportcard_subscription_end_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionTransaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_days', models.PositiveIntegerField()),
                ('payment_method', models.CharField(choices=[('cash', 'Cash')], default='cash', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_transactions', to='PTP.transportcard')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscription_sales', to=settings.AUTH_USER_MODEL)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscription_transactions', to='PTP.zone')),
            ],
            options={
                'db_table': 'subscription_transaction',
            },
        ),
    ]
