# Generated by Django 4.2.7 on 2026-08-04 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PTP', '0030_subscriptiontransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='daily_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='zone',
            name='monthly_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='zone',
            name='weekly_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
