# Generated by Django 4.2.7 on 2026-08-07 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PTP', '0031_zone_daily_price_zone_monthly_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transportcard',
            name='subscription_end',
        ),
        migrations.RemoveField(
            model_name='transportcard',
            name='subscription_start',
        ),
        migrations.RemoveField(
            model_name='transportcard',
            name='subscription_zone',
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='route',
            field=models.ForeignKey(blank=True, help_text='The route whose zone was checked. Null if no trip was resolved.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_transactions', to='PTP.route'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='trip',
            field=models.ForeignKey(blank=True, help_text='The active trip during which the scan occurred. Null for attempts rejected before a trip could be resolved (e.g. card not found, card inactive).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_transactions', to='PTP.drivertrip'),
        ),
    ]
