# Generated by Django 4.2.7 on 2026-04-17 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PTP', '0013_route_end_latitude_route_end_longitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverTrip',
            fields=[
                ('trip_id', models.AutoField(db_column='trip_id', primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed')], default='active', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='PTP.driver')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='PTP.route')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='PTP.vehicle')),
            ],
            options={
                'db_table': 'driver_trip',
            },
        ),
        migrations.CreateModel(
            name='VehicleLocation',
            fields=[
                ('location_id', models.AutoField(db_column='location_id', primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('speed_kmh', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('heading', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='PTP.driver')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='PTP.drivertrip')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='PTP.vehicle')),
            ],
            options={
                'db_table': 'vehicle_location',
                'ordering': ['-recorded_at'],
            },
        ),
    ]
