# Generated by Django 4.2.7 on 2026-04-17 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PTP', '0014_drivertrip_vehiclelocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclelocation',
            name='distance_to_route_meters',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='vehiclelocation',
            name='is_off_route',
            field=models.BooleanField(default=False),
        ),
    ]
